apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-slallemand
  namespace: openshift-gitops
spec:
  project: backstage
  source:
    repoURL: https://github.com/Janus-france-ssa/janus-gitops.git
    targetRevision: slallemand/openshift-authent
    path: gitops/backstage/overlays/slallemand
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage-slallemand
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: false
      prune: false
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
