apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/RedHat-Summit-Connect-France-2023/gitops.git
    targetRevision: main
    path: gitops/kubevirt/base
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
