apiVersion: v1
kind: Namespace
metadata:
  name: backstage 
  annotations:
    openshift.io/node-selector: ""
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: janus-argocd
  annotations:
    openshift.io/node-selector: ""
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "Advanced Cluster Management for Kubernetes"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: open-cluster-management
---
apiVersion: v1
kind: Namespace
metadata:
  name: kepler
  annotations:
    openshift.io/node-selector: ""
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
