apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kepler
  namespace: openshift-gitops
spec:
  project: backstage
  source:
    repoURL: https://github.com/RedHat-Summit-Connect-France-2023/gitops.git
    targetRevision: main
    path: gitops/kepler/base
  destination:
    server: https://kubernetes.default.svc
    namespace: kepler
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: false
      prune: false
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
