apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- files:
  - app-config.yaml
  name: app-config
  behavior: create

resources:
- ./backstage-deployment.yaml
- ./backstage-sa.yaml
- ./postgres-deployment.yaml
