apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      containers:
      - name: postgres
        image: registry.redhat.io/rhel8/postgresql-12:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_USER
          value: "pg"
        - name: POSTGRESQL_PASSWORD
          value: "redhat"
        - name: POSTGRESQL_DATABASE
          value: "postgres"
        - name: POSTGRESQL_PORT
          value: "5432"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/pgsql/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  type: ClusterIP
---
