apiVersion: v1
kind: Secret
metadata:
  name: jboss-eap-cloudinit
type: Opaque
stringData:
  userData: |
    #cloud-config

    users:
    - name: admin
      gecos: French SA Team
      groups: wheel
      lock_passwd: false
      # echo REDACTED | mkpasswd --method=yescrypt -s
      passwd: $y$j9T$LEafblWZP3V52Cbzt6QLW/$kcwkvEonHMJj0F.JkiDXZTqBakv5OBD/AJZc5Ba5KhC
      ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFW62WJXI1ZCMfNA4w0dMpL0fsldhbEfULNGIUB0nQui nmasse@redhat.com

    write_files:
    - path: /etc/default/jboss-eap.conf
      content: |
        ## Location of JDK
        JAVA_HOME="/usr/lib/jvm/java-1.8.0"

        ## Location of JBoss EAP
        JBOSS_HOME="/opt/jboss-eap-7.0"

        ## The username who should own the process.
        JBOSS_USER=jboss

        ## The mode JBoss EAP should start, standalone or domain
        JBOSS_MODE=standalone

        ## Configuration for standalone mode
        JBOSS_CONFIG=standalone-full.xml

        ## The amount of time to wait for startup
        # STARTUP_WAIT=60

        ## The amount of time to wait for shutdown
        # SHUTDOWN_WAIT=60

        ## Location to keep the console log
        JBOSS_CONSOLE_LOG="/var/log/jboss-eap/console.log"

        ## Additionals args to include in startup
        # JBOSS_OPTS="--admin-only -b 127.0.0.1"
      permissions: '0440'
      append: false

    - path: /etc/sudoers
      content: |
        Defaults   !visiblepw
        Defaults    always_set_home
        Defaults    match_group_by_gid
        Defaults    always_query_group_plugin
        Defaults    env_reset
        Defaults    env_keep =  "COLORS DISPLAY HOSTNAME HISTSIZE KDEDIR LS_COLORS"
        Defaults    env_keep += "MAIL QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE"
        Defaults    env_keep += "LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES"
        Defaults    env_keep += "LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE"
        Defaults    env_keep += "LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY"
        Defaults    secure_path = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin
        root    ALL=(ALL)       ALL
        %wheel  ALL=(ALL)       NOPASSWD: ALL
        #includedir /etc/sudoers.d
      permissions: '0440'
      append: false

    - path: /root/bootstrap.sh
      content: |
        #!/bin/bash
        set -Eeuo pipefail
        curl -sSfL https://redhat-summit-connect-france-2023.s3.eu-west-3.amazonaws.com/jboss-eap.tar | tar -x '--pax-option=delete=SCHILY.*,delete=LIBARCHIVE.*' --exclude '.*' -C /opt
        cd /opt/jboss-eap-7.0
        cp bin/init.d/jboss-eap-rhel.sh /etc/init.d
        chmod +x /etc/init.d/jboss-eap-rhel.sh
        restorecon -F /etc/init.d/jboss-eap-rhel.sh
        chkconfig --add jboss-eap-rhel.sh
        chkconfig jboss-eap-rhel.sh on
        exit 0
      permissions: '0755'

    packages:
    - java-1.8.0-openjdk-headless
    - initscripts

    runcmd:
    - [ "/root/bootstrap.sh" ]
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: jboss-eap
  name: jboss-eap
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: jboss-eap
      spec:
        source:
          http:
            url: https://redhat-summit-connect-france-2023.s3.eu-west-3.amazonaws.com/Fedora-Cloud-Base-38-1.6.x86_64.qcow2
        pvc:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 6Gi
  runStrategy: Always
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: large
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: jboss-eap
        kubevirt.io/size: large
    spec:
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - macAddress: '02:cd:c0:00:00:00'
              masquerade: {}
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel8.4.0
        resources:
          requests:
            memory: 8Gi
      evictionStrategy: LiveMigrate
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: jboss-eap
          name: rootdisk
        - cloudInitNoCloud:
            secretRef:
              name: jboss-eap-cloudinit
          name: cloudinitdisk
---
apiVersion: v1
kind: Service
metadata:
  name: jboss-eap
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: psql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    kubevirt.io/domain: jboss-eap
  type: ClusterIP